baseurl = "/"
languageCode = "en-us"
theme = "steam"

# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 5

[params]
	title = "Meow"
	subtitle = "Thoughts, ideas, and works."
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor = "green"

	# Link custom assets relative to /static
	favicon   = "/img/fav.ico"
	customCSS = []
	customJS  = []

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Dylan Fontana"
	bio = "Insert bio here."
	description = "Your description of the blog"
	
	# Link your social networks (optional)
	location = "America/New_York"
	linkedin = "dylan-fontana"
	github = "dfontana"
    googleplus = ""
	facebook = ""
	instagram = ""
	gitlab = ""
	bitbucket = ""

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"

[Menus.main]
    [Home]
        Name = "Home"
        URL = "/"
    [About] 
        Name = "About"
        URL = "/about/"
    [Projects] 
        Name = "Projects"
        URL = "/projects/"    