base_url = "https://dfontana.github.io"
title = "Frontiers"
description = "Thoughts, ideas, and works."
theme="after-dark"
highlight_code = true
highlight_theme = "solarized-dark"
compile_sass = true
taxonomies = [
    # You can enable/disable RSS
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

build_search_index = true

[extra]
after_dark_menu = [
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

    [extra.footer]
    author = "Dylan Fontana"
    profile = "/img/profile.png"
    bio = "Explore, learn, and pursue - three of my favorite things."
    location = "America/Boston"
