base_url = "https://dfontana.github.io"
title = "Frontiers"
description = "Thoughts, ideas, and works."
compile_sass = true
taxonomies = [
    {name = "categories", rss = true},
    {name = "tags", rss = true},
]

build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "solarized-dark"

[extra]
menu = [
    {url = "$BASE_URL/categories", mobile=true, name = "Categories"},
    {url = "$BASE_URL/tags", mobile=true, name = "Tags"},
    {url = "$BASE_URL/about", mobile=false, name = "About"},
]

    [extra.footer]
    author = "Dylan Fontana"
    profile = "/img/profile.png"
    bio = "Explore, learn, and pursue - three of my favorite things."
    location = "America/Boston"
