baseurl         = "/"
languageCode    = "en-us"
theme           = "steam"
googleAnalytics = "" # Enable Google Analytics; insert tracking code
paginate        = 5  # Number of posts per page

[params]
	title       = "Meow"
	subtitle    = "Thoughts, ideas, and works."
	copyright   = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themecolor  = "green"

	# Link custom assets relative to /static
	favicon     = "/img/fav.ico"
	customCSS   = []
	customJS    = []

	# To provide some metadata for search engines and footer about.
	name        = "Dylan Fontana"
	bio         = "Insert bio here."
	description = "Your description of the blog"
	
	# Link your social networks
	location    = "America/New_York"
	linkedin    = "dylan-fontana"
	github      = "dfontana"
    googleplus  = ""
	facebook    = ""
	instagram   = ""
	gitlab      = ""
	bitbucket   = ""

	# Customize or translate the strings
	keepReadingStr      = "Keep reading"
	backtotopStr        = "Back to top"
	shareStr            = "Share"
	pageNotFoundTitle   = "404 - Page not found"