base_url = "https://nill.ink"
title = "nill.ink"
description = "Thoughts, ideas, and works."
compile_sass = true
taxonomies = [
    {name = "tags", rss = true},
]

[markdown]
render_emoji = true
external_links_no_follow = true

[markdown.highlighting]
enabled = true
theme = "rose-pine-dawn"

[link_checker]
skip_anchor_prefixes = [
    "https://github.com/",
]

[extra]
menu = [
    {url = "$BASE_URL/frontier", name = "Frontiers"},
    {url = "$BASE_URL/about", name = "About"},
]

    [extra.bio]
    author = "Dylan Fontana"
    profile = "/img/profile.png"
    avatar = "/img/icon-bronze.png"
    bio = "Explore, Learn, Pursue."
    display_location = "Boston"

    [[extra.bio.socials]]
    faicon = "github"
    link = "https://github.com/dfontana"

    [[extra.bio.socials]]
    faicon = "linkedin"
    link = "https://linkedin.com/in/dylan-fontana"
