base_url = "https://dfontana.github.io"
title = "Frontiers"
description = "Thoughts, ideas, and works."
compile_sass = true
taxonomies = [
    {name = "tags", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "zenburn"
render_emoji = true
external_links_no_follow = true

[extra]
menu = [
    {url = "$BASE_URL/about", name = "About"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/ark", name = "Ark"}
]

    [extra.footer]
    author = "Dylan Fontana"
    profile = "/img/profile.png"
    bio = "Explore, learn, and pursue - three of my favorite things."
    location = "America/Boston"
