base_url = "https://dfontana.github.io"
title = "Dylan Fontana"
compile_sass = true
taxonomies = [
    {name = "tags", rss = true},
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"
render_emoji = true
external_links_no_follow = true

[extra]
menu = [
    {url = "$BASE_URL/posts", name = "Frontiers"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]

    [extra.bio]
    author = "Dylan Fontana"
    profile = "/img/profile.png"
    avatar = "/img/icon-bronze.png"
    bio = "Explore, Learn, Pursue."
    location = "America/Boston"

    [[extra.bio.socials]]
    faicon = "github"
    link = "https://github.com/dfontana"

    [[extra.bio.socials]]
    faicon = "linkedin"
    link = "https://linkedin.com/in/dylan-fontana"
