name: Build and deploy GH Pages
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    name: Validate Compilation
    if: github.ref != 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Compile
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_deploy:
    runs-on: ubuntu-latest
    name: Deploy to Prod
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Deploy
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          BUILD_DIR: .
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
